import fs from 'node:fs/promises'
import path from 'node:path'
import { execFile, execSync } from 'node:child_process'
import { promisify } from 'node:util'

const exec = promisify(execFile)

export type ClaimInputs = {
  credential: string
  claimant: string
  sources: Array<{ repo: string; commits: string[] }>
  claimId: string
}

export type PublishInputs = {
  targetRepo: string
  sourceDir: string
  destinationPath: string
  branch: string
  commitMessage: string
}

export interface ForgeProvider {
  providerName(): string
  getUser(): Promise<string>
  getIssueUrl(repo: string, number: number): Promise<string>
  createIssue(repo: string, title: string, body: string): Promise<number>
  createPullRequest(repo: string, branch: string, title: string): Promise<number>
  openPullRequestForBranch(
    targetRepo: string,
    sourceRepo: string,
    sourceBranch: string,
    title: string,
    body: string,
  ): Promise<number>
  getIssueStatus(repo: string, issueNumber: number): Promise<{ state: string; labels: string[]; url: string }>
  listClaimProcessingRuns(repo: string, issueNumber: number): Promise<
    Array<{
      status: string
      conclusion?: string | null
      url: string
      name?: string
      createdAt?: string
      workflowName?: string
    }>
  >
  listClaimIssues(repo: string): Promise<
    Array<{
      number: number
      title: string
      state: string
      body?: string
      url?: string
      labels?: Array<{ name: string }>
    }>
  >
  cloneRepo(fullName: string, destination: string): Promise<void>
  copyDirectory(source: string, destination: string): Promise<void>
}

function hasGh(): boolean {
  try {
    execSync('which gh', { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
}

async function runGh(args: readonly string[]): Promise<string> {
  if (!hasGh()) {
    throw new Error('gh CLI is required for this workflow')
  }
  const result = await exec('gh', args, { encoding: 'utf8' })
  return result.stdout.trim()
}

async function copyDirRecursively(source: string, target: string): Promise<void> {
  await fs.mkdir(target, { recursive: true })
  const entries = await fs.readdir(source, { withFileTypes: true })
  for (const entry of entries) {
    if (entry.name === '.git') {
      continue
    }
    const from = path.join(source, entry.name)
    const to = path.join(target, entry.name)
    if (entry.isDirectory()) {
      await copyDirRecursively(from, to)
      continue
    }
    if (entry.isSymbolicLink()) {
      const link = await fs.readlink(from)
      await fs.symlink(link, to)
      continue
    }
    if (entry.isFile()) {
      await fs.copyFile(from, to)
    }
  }
}

export class GitHubProvider implements ForgeProvider {
  providerName(): string {
    return 'gh'
  }

  async getUser(): Promise<string> {
    return await runGh(['api', 'user', '--jq', '.login'])
  }

  async getIssueUrl(repo: string, number: number): Promise<string> {
    return `https://github.com/${repo}/issues/${number}`
  }

  async createIssue(repo: string, title: string, body: string): Promise<number> {
    const raw = await runGh([
      'issue',
      'create',
      '-R',
      repo,
      '--title',
      title,
      '--body',
      body,
      '--label',
      'skillcraft-claim',
    ])
    const match = raw.match(/\b(\d+)$/)
    if (!match) {
      return 0
    }
    return Number(match[1])
  }

  async createPullRequest(targetRepo: string, branch: string, title: string): Promise<number> {
    const raw = await runGh([
      'pr',
      'create',
      '--repo',
      targetRepo,
      '--head',
      branch,
      '--base',
      'main',
      '--title',
      title,
      '--body',
      `Generated by skillcraft for ${title}`,
      '--fill-first',
    ])
    const match = raw.match(/\b(\d+)$/)
    if (!match) {
      return 0
    }
    return Number(match[1])
  }

  async openPullRequestForBranch(
    targetRepo: string,
    sourceRepo: string,
    sourceBranch: string,
    title: string,
    body: string,
  ): Promise<number> {
    const raw = await runGh([
      'pr',
      'create',
      '--repo',
      targetRepo,
      '--head',
      `${sourceRepo}:${sourceBranch}`,
      '--base',
      'main',
      '--title',
      title,
      '--body',
      body,
    ])
    const match = raw.match(/\b(\d+)$/)
    if (!match) {
      return 0
    }
    return Number(match[1])
  }

  async getIssueStatus(repo: string, issueNumber: number): Promise<{ state: string; labels: string[]; url: string }> {
    const raw = await runGh(['issue', 'view', String(issueNumber), '--repo', repo, '--json', 'state,labels,url'])
    const parsed = JSON.parse(raw) as { state: string; labels: Array<{ name: string }>; url: string }
    return {
      state: parsed.state,
      labels: parsed.labels?.map((label) => label.name) ?? [],
      url: parsed.url,
    }
  }

  async listClaimProcessingRuns(repo: string, issueNumber: number): Promise<
    Array<{
      status: string
      conclusion?: string | null
      url: string
      name?: string
      createdAt?: string
      workflowName?: string
    }>
  > {
    const raw = await runGh([
      'run',
      'list',
      '--repo',
      repo,
      '--workflow',
      'Process credential claims',
      '--json',
      'name,status,conclusion,url,createdAt,workflowName',
    ])
    const parsed = JSON.parse(raw) as Array<{
      status?: string
      conclusion?: string | null
      url?: string
      name?: string
      createdAt?: string
      workflowName?: string
    }>
    const issueMarker = `#${issueNumber}`

    const candidates = parsed.filter((entry) => {
      const name = entry.name || ''
      const workflowName = entry.workflowName || ''
      return name.includes(issueMarker) || workflowName.includes(issueMarker)
    })

    const runs = candidates.length > 0
      ? candidates
      : parsed.filter((entry) => entry.status && ['in_progress', 'queued', 'waiting', 'action_required', 'canceling'].includes(entry.status))
    if (!runs.length) {
      return []
    }

    return runs
      .filter((entry) => entry.url)
      .map((entry) => ({
        status: entry.status || 'unknown',
        conclusion: entry.conclusion ?? undefined,
        url: entry.url!,
        name: entry.name,
        createdAt: entry.createdAt,
        workflowName: entry.workflowName,
      }))
  }

  async listClaimIssues(repo: string): Promise<
    Array<{
      number: number
      title: string
      state: string
      body?: string
      url?: string
      labels?: Array<{ name: string }>
    }>
  > {
    const raw = await runGh([
      'issue',
      'list',
      '--repo',
      repo,
      '--label',
      'skillcraft-claim',
      '--state',
      'all',
      '--json',
      'number,title,state,body,labels,url',
      '--limit',
      '50',
    ])
    const parsed = JSON.parse(raw) as Array<{
      number: number
      title: string
      state: string
      body?: string
      labels?: Array<{ name: string }>
      url?: string
    }>
    return parsed
  }

  async cloneRepo(fullName: string, destination: string): Promise<void> {
    const temp = path.resolve(destination)
    await runGh(['repo', 'clone', fullName, temp])
  }

  async copyDirectory(source: string, destination: string): Promise<void> {
    const info = await fs.readdir(destination).catch(() => undefined)
    if (info) {
      await fs.rm(destination, { recursive: true, force: true })
    }
    await fs.mkdir(destination, { recursive: true })
    await copyDirRecursively(source, destination)
  }
}
